SELECT CAST(SALARY*MONTHS AS VARCHAR) + "  " + CAST(COUNT(*) AS VARCHAR) FROM EMPLOYEE
WHERE SALARY*MONTHS NOT IN (
    SELECT E1.SALARY*E1.MONTHS FROM EMPLOYEE E1
    JOIN EMPLOYEE E2
    ON E1.SALARY*E1.MONTHS < E2.SALARY*E2.MONTHS
    )
GROUP BY SALARY*MONTHS
;

